configurationset:
  - configuration:
      name: spotify_config
      client_id: 
      client_secret: 
      buffer: A BASE-64 ENCODED ID:SECRET HASH
  - configuration:
      name: unsplash_api_key
      unsplash_clientId: 
  - configuration:
      name: openweather_api_key
      openweather_api_key: 